### ISSUE TITLE
Module readability

### ISSUE THREAD

**Issue by davestephens** [majkinetor/psinflux#3]
Not necessarily an issue per-se, but this module is a nightmare to understand at first glace due to the over-use of aliases and badly-named functions. 

e.g. - a function name should give an idea of what the function does, without having to read the code within it;

```
function ir([string]$q) {
    if (!$Env:INFLUX_SERVER) {throw "Define `$Env:INFLUX_SERVER to use this module"}
    $r = "$Env:INFLUX_SERVER/query?q=$q"
    irm $r -UseBasicParsing
}
```
This is bad on two parts - it has a terrible name, and you're expected to know that `irm` is an alias for Invoke-RestMethod. I'm reasonably handy with PS, but still found myself looking them up.

Would you accept a PR to clean this up inline with the PowerShell Style Guide?

**Comment by majkinetor** [comment]
Yeah, its a quick module done over the several days and I didn't devote any time in polishing it. `ir` means _influx request_. I usually document my stuff well but this is obviously an exception because I wasn't sure if I would need more coding to make it useful everywhere where I need it, plus statsd part was lacking in design.

> Would you accept a PR to clean this up inline with the PowerShell Style Guide?

It depends on what you do. Submit PR and I will review it. If you do expand aliases, do not expand % and ? or I wont accept it. Removing handy every day aliases of the module itself is no-go for me to, `iq` (influx query) and `iqr` (influx query raw) because I actually use them every day and they are for end user.

Thanks for comments.

**Comment by davestephens** [comment]
I had intended to bring it in line with PS style guide best practises, so yeah, all aliases would be removed. Whilst most people know what they are (`% = Foreach-Object etc`), it removes clarity and readability especially for those less adept at Powershell, which isn't a good thing whichever way you want to cut it. 

> If you do expand aliases, do not expand % and ? or I wont accept it. Removing handy every day aliases of the module itself is no-go for me 

I don't understand the logic behind this. What difference does it make if the code is tucked away in a module?

**Comment by davestephens** [comment]
Also;

> Removing handy every day aliases of the module itself is no-go for me to, iq (influx query) and iqr (influx query raw) because I actually use them every day and they are for end user.

This doesn't prevent the functions being named with a more verbose name, you'd simply alias them within the module so that you still have shortcuts that you find handy.

**Comment by majkinetor** [comment]
I dont want to talk about aliases as I had done that more times then I like. You can replace all except ? or %. You can rename funcs and provide aliases, no problem. 

> I don't understand the logic behind this. What difference does it make if the code is tucked away in a module?

I can tell the same 4 this entire issue. 

The maintainer will care, just like you do.

**Comment by davestephens** [comment]
I was trying to help improve your code for your benefit and others, but you don't seem open to it (which seems strange given you've open sourced it) - so I'll just go merrily on my way :-) Have a read of the PowerShell Style Guide - there are some neat ideas in there, which if you want collaboration on your project (and I assume you do as it's a public repo) will help you and others out. https://github.com/PoshCode/PowerShellPracticeAndStyle
